name: Django ci/cd

on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PG_NAME: ${{ secrets.PG_NAME }}
      PG_USER: ${{ secrets.PG_USER }}
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      PG_HOST: ${{ secrets.PG_HOST }}
      PG_PORT: ${{ secrets.PG_PORT }}
    services:
      postgres_main: 
        image: postgres:latest
        env: 
          POSTGRES_USERS: ${{ env.PG_USER }}
          POSTGRES_PASSWORD: ${{ env.PG_PASSWORD }}
          POSTGRES_DB: ${{ env.PG_NAME }}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready 
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check changes
        uses: actions/checkout@v2
      - name: python install
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: check files
        run: ls -l

      - name: install requirements
        run: pip install -r requirements.txt
      
      - name: start tests
        run: python webpython/manage.py test
        env:
          PG_NAME: ${{ env.PG_NAME }}
          PG_USER: ${{ env.PG_USER }}
          PG_PASSWORD: ${{ env.PG_PASSWORD }}
          PG_HOST: ${{ env.PG_HOST }}
          PG_PORT: ${{ env.PG_PORT }}
  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secret.SSH_HOST }}
          username: ${{ secret.SSH_USERNAME }}
          key: ${{ secret.SSH_KEY }}
          script: |
            ls -l
